@startuml

abstract class Template {
    methodA()
    methodB()
    methodC()
}

class Concrete1 {
    methodA()
    methodB()
    methodC()
}

class Concrete2 {
    methodA()
    methodB()
    methodC()
}

Template <|-- Concrete1
Template <|-- Concrete2

@enduml